/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LocacoesRouteImport } from './routes/locacoes'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as FrotaInternaRouteImport } from './routes/frota-interna'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacoesRoute = LocacoesRouteImport.update({
  id: '/locacoes',
  path: '/locacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaInternaRoute = FrotaInternaRouteImport.update({
  id: '/frota-interna',
  path: '/frota-interna',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/frota-interna': typeof FrotaInternaRoute
  '/licitacoes': typeof LicitacoesRoute
  '/locacoes': typeof LocacoesRoute
  '/manutencao': typeof ManutencaoRoute
  '/obras': typeof ObrasRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/frota-interna': typeof FrotaInternaRoute
  '/licitacoes': typeof LicitacoesRoute
  '/locacoes': typeof LocacoesRoute
  '/manutencao': typeof ManutencaoRoute
  '/obras': typeof ObrasRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/frota-interna': typeof FrotaInternaRoute
  '/licitacoes': typeof LicitacoesRoute
  '/locacoes': typeof LocacoesRoute
  '/manutencao': typeof ManutencaoRoute
  '/obras': typeof ObrasRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/compras'
    | '/documentos'
    | '/equipamentos'
    | '/equipe'
    | '/financeiro'
    | '/frota-interna'
    | '/licitacoes'
    | '/locacoes'
    | '/manutencao'
    | '/obras'
    | '/solicitacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/compras'
    | '/documentos'
    | '/equipamentos'
    | '/equipe'
    | '/financeiro'
    | '/frota-interna'
    | '/licitacoes'
    | '/locacoes'
    | '/manutencao'
    | '/obras'
    | '/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/compras'
    | '/documentos'
    | '/equipamentos'
    | '/equipe'
    | '/financeiro'
    | '/frota-interna'
    | '/licitacoes'
    | '/locacoes'
    | '/manutencao'
    | '/obras'
    | '/solicitacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  DocumentosRoute: typeof DocumentosRoute
  EquipamentosRoute: typeof EquipamentosRoute
  EquipeRoute: typeof EquipeRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FrotaInternaRoute: typeof FrotaInternaRoute
  LicitacoesRoute: typeof LicitacoesRoute
  LocacoesRoute: typeof LocacoesRoute
  ManutencaoRoute: typeof ManutencaoRoute
  ObrasRoute: typeof ObrasRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacoes': {
      id: '/locacoes'
      path: '/locacoes'
      fullPath: '/locacoes'
      preLoaderRoute: typeof LocacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota-interna': {
      id: '/frota-interna'
      path: '/frota-interna'
      fullPath: '/frota-interna'
      preLoaderRoute: typeof FrotaInternaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  DocumentosRoute: DocumentosRoute,
  EquipamentosRoute: EquipamentosRoute,
  EquipeRoute: EquipeRoute,
  FinanceiroRoute: FinanceiroRoute,
  FrotaInternaRoute: FrotaInternaRoute,
  LicitacoesRoute: LicitacoesRoute,
  LocacoesRoute: LocacoesRoute,
  ManutencaoRoute: ManutencaoRoute,
  ObrasRoute: ObrasRoute,
  SolicitacoesRoute: SolicitacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
